name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Set up known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy EC2 private key
        run: |
          echo "${{ secrets.EC2_EXPRESS_REDIS_SERVER_PEM }}" > ec2_private_key.pem
          chmod 600 ec2_private_key.pem

      - name: install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380

      - name: SSH and deploy
        run: |
          ssh -i "${{ secrets.EC2_EXPRESS_REDIS_SERVER_PEM }}" \
          ${{ secrets.EC2_USER_NAME }}@ec2-43-203-13-71.ap-northeast-2.compute.amazonaws.com << EOF

          # Ubuntu 패키지 업데이트
          sudo apt-get update
          sudo apt-get upgrade -y

          # Node.js 18.x 설치
          sudo apt-get remove nodejs
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # 작업 디렉터리로 이동
          cd express-redis-server/

          # 다음 명령어를 순차적으로 실행합니다
          sudo git pull || exit 1
          sudo npm install || exit 1
          sudo npm run build || exit 1
          sudo pm2 delete all || exit 1
          sudo pm2 start npm -- start || exit 1

          EOF
