name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      # - name: Copy EC2 private key
      #   run: |
      #     echo "${{ secrets.EC2_EXPRESS_REDIS_SERVER_PEM }}" > ~/.ssh/express-redis-server.pem
      #     chmod 600 ~/.ssh/express-redis-server.pem

      - name: Install pm2
        run: sudo npm install -g pm2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script_stop: true
          script: |
            cd express-redis-server/
            sudo apt-get update
            sudo git pull || exit 1
            sudo npm install || exit 1
            sudo npm run build || exit 1

            # 현재 실행중인 pm2 를 모두종료 
            sudo pm2 delete all

            # PM2 목록을 가져와 로그로 출력
            sudo pm2 list

            # PM2로 프로세스를 재시작 !
            sudo pm2 restart 0
