name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Set up known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy EC2 private key
        run: |
          echo "${{ secrets.EC2_EXPRESS_REDIS_SERVER_PEM }}" > express-redis-server.pem
          chmod 600 express-redis-server.pem

      # - name: install and run redis-server
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y redis-server
      #     redis-server --daemonize yes --requirepass test_env --port 6380

      # - name: SSH and deploy
      #   run: |
      #     ssh -i "express-redis-server.pem" \
      #     "${{ secrets.EC2_USER_NAME }}"@ec2-43-203-13-71.ap-northeast-2.compute.amazonaws.com
      - name: SSH and deploy
        run: |
          ssh -i "${{ secrets.EC2_EXPRESS_REDIS_SERVER_PEM }}" \
          "${{ secrets.EC2_USER_NAME }}"@ec2-43-203-13-71.ap-northeast-2.compute.amazonaws.com << EOF
          # Your commands to run on the remote server go here
                    # # Ubuntu 패키지 업데이트
          # sudo apt-get update
          # sudo apt-get upgrade -y
          EOF
